### ISSUE TITLE
Key Bind

### ISSUE THREAD

**Issue by paintrain76** [tropicalpunchy/ahk-csgo-bhop-script#2]
Can     the    key    be    changed    to    mouse4   ?   if    so   how      ?

**Comment by tropicalpunchy** [comment]
If you are referring to the button to toggle the script on/off then yes! If you edit the script with something like notepad, you can change where it says f8 and change that to either XButton2 or XButton1 (these are mouse buttons 4 and 5 for auto hot key). Let me know if that helps.

**Comment by paintrain76** [comment]
Thank you very much, I was referring to the bhop keys...
